### ISSUE TITLE
Some installation observations

### ISSUE THREAD

**Issue by zell-mbc** [leiweibau/Pi.Alert#17]
Posting here as well after I seem to have been chasing the wrong repo.

After my first issue https://github.com/jokob-sk/Pi.Alert/issues/56 was resolved by manually adding a db file I ran into another issue right away when when trying to change some details of a device. The UI reported that the DB is read only. After playing around with groups and user rights for a while I gave up on Docker and went for a native install on my PiHole (DietPi OS)

First observation, the detailed installation link points to the wrong package: curl -LO https://github.com/leiweibau/Pi.Alert/Pi.Alert/raw/main/tar/pialert_latest.tar Pucherot, insteat of leiweibau.
I didn't notice and it did install nevertheless but I obviously got the version without your new maintenance screen. This version also showed the "DB is read only error"? 

After I noticed that I got the wrong link I started all over with the links from your main page https://github.com/jokob-sk/Pi.Alert
Given that I am already running PiHole I went with the second link which worked, answered all the questions but then the installation stopped with
```
…
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'

- Deleting downloaded tar file...
- Settting Pi.Alert config file
sed: can't read /home/thomas/pialert/config/pialert.conf: No such file or directory
…
```

The error is correct because somehow the installer didn't install the directories in /home/thomas/pialert but in ~ (/home/thomas)
I tried to launch a second time from within a manually created ~/pialert folder which didn't work because the folder was already there.

So I moved all folders manually to ~/pialert and updated the pialert directory in the config file manualy followed by running one of the cron commands:
`python3 ~/pialert/back/pialert.py 1
`
This time it was complaining about a table "Online_History"

`sqlite3.OperationalError: table Online_History has no column named Archived_Devices
`
So I went ahead and moved the template DB I used yesterday over the newly created database, but this one doesn't seem to have the table Online_History at all?
```
python3 ~/pialert/back/pialert.py 1
sqlite3.OperationalError: no such table: Online_History
```

I then discovered the pialert_patch_DB.sh script which adds the missing table, but after running that one I am stuck with
`sqlite3.OperationalError: table Online_History has no column named ScanCycle
`

Here's a screenshot of the "DB read only" error I got on the Docker install as well as now on my PiHole:

![image](https://user-images.githubusercontent.com/29018767/182125578-a8a774fc-e6d2-4b82-b956-4e6e65513d45.png)

There's another DB related issue when trying to create a backup (both on Docker and PiHole), after confirming that I am sure I want to create a backup I get the following error(?)
![image](https://user-images.githubusercontent.com/29018767/182128709-fa02aec6-0939-4f5f-983d-5e961bd988a5.png)

Lastly, I read somewhere that using 'SCAN_SUBNETS    = '--localnet --interface=eth0' speeds up operation of the arp scan. Seems like this is not working though.
When I use the interface option I run into a Python error.
Section 1 below shows the active setting, section 2 the error an section 3 a manual run of arp-scan with the interface option.

```
thomas in pihole in ~ took 2s
% cat pialert/config/pialert.conf | grep SCAN_SUBNETS
# SCAN_SUBNETS    = '--localnet'
# SCAN_SUBNETS    = '192.168.11.0/24 192.168.144.0/24'
SCAN_SUBNETS    = '--localnet --interface=eth0'
#SCAN_SUBNETS      = '--localnet'

% python3 ~/pialert/back/pialert.py 1

Pi.Alert 3.5_leiweibau (2022-07-07)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2022-08-01 15:59:00

Scanning...
    arp-scan Method...
arp-scan: unrecognized option '--localnet --interface=eth0'
Traceback (most recent call last):
  File "/home/thomas/pialert/back/pialert.py", line 1576, in <module>
    sys.exit(main())       
  File "/home/thomas/pialert/back/pialert.py", line 88, in main
    res = scan_network()
  File "/home/thomas/pialert/back/pialert.py", line 366, in scan_network
    arpscan_devices = execute_arpscan (arpscan_retries)
  File "/home/thomas/pialert/back/pialert.py", line 474, in execute_arpscan
    arpscan_output = subprocess.check_output (arpscan_args, universal_newlines=True)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'arp-scan', '--ignoredups', '--bandwidth=512k', '--retry=3', '--localnet --interface=eth0']' returned non-zero exit status 1.

thomas in pihole in ~
1 % sudo arp-scan --localnet --interface=eth0
Interface: eth0, type: EN10MB, MAC: dc:a6:32:42:99:ca, IPv4: 175.0.0.5
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)
175.0.0.1       2c:91:ab:97:98:e4       (Unknown)
…
18 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.7: 256 hosts scanned in 2.242 seconds (114.18 hosts/sec). 17 responded

```

**Comment by leiweibau** [comment]
With your hints and related problems, I agree with you without any excuse. I just created a new archive with the orginal script to pack the archive and changed the name to my username without testing much if the installation works. That was a mistake.

As for the missing table in the database, here jokob-sk and I proceed differently. In the folder install is a shellscript, which patches the DB. That the hint for this is unfortunately only in the commit and not in the readme is also my fault. I will change this, or add an already patched database to the archive.

So last would be the scan with other extended parameters. Since I have a /16 network configured, I use a different scan and also do without the scan cycles. At that moment (because not tested) other parameters do not work. Also here I will probably have to adjust my fork again, or at least give a clear hint in the readme.

To enable the original scan comment folder back in the file pialert.py the line 459 out and remove '# ' in line 462. Then everything should work normally.

Thanks for the critique. I have only focused on the frontend so far and was confident that my changes would not affect the installation process.

**Comment by leiweibau** [comment]
About the error "The original database could not be saved": At this point the script tries to create a copy of the database to compress it. It seems that the user running PHP does not have write permission to the database directory. But PHP needs this permission to be able to write to the database and to create the backup. Without the write permission in this folder also the language change or other optical settings are not possible.

**Comment by leiweibau** [comment]
The DB, which is include in the archive, already has the table Online_History included. I have just checked. 

However, regardless of my failings, I would like to mention that I could not get the original Pi Alert to run on a DietPi 8.x even after several hours.

**Comment by jokob-sk** [comment]
Hey, I just updated the Installation notes, will update it further if you
have some specific installation steps for your fork:
https://github.com/jokob-sk/Pi.Alert/tree/fix-merge-5

**Comment by zell-mbc** [comment]
Great, thanks for looking into my issues.
I am offline für the next two days but will look into this asap after my return.

1 Aug 2022 22:14:12 leiweibau ***@***.***>:

**Comment by leiweibau** [comment]
The DB is fixed, and a new archive is uploaded. On RasbianOS the installation proceed without errors and at the end everything works fine. On Dietpi i haven't test it yet.

**Comment by zell-mbc** [comment]
Looks like all problems are solved with this latest build. On my DietPi I had to install pip/requests first but after that everything seems to work.
```
sudo apt-get install pip
python3 -m pip install requests
```
- Installation worked
- Updating devices works
- Backing up the DB works

The only thing I need to figure out is where the ~150 devices with no IP or any other data are coming from.

![image](https://user-images.githubusercontent.com/29018767/182606072-40e5680c-3edb-4435-898b-60380101db35.png)

**Comment by leiweibau** [comment]
Check out the Network Page in Pihole->Tools->Network. Perhaps there are some "dead" hosts.

**Comment by zell-mbc** [comment]
Indeed, that's where they are coming from. Great, thanks!
Maybe a quick UI suggestion, how about closing the Device-Details screen when "Save" is selected? Would save a click when one gets started with updating the device list.

**Comment by leiweibau** [comment]
I'm thinking of adding a small FAQ that also covers this topic

You can navigate forward and backward on the details page in the upper right corner. When the save closes this page, the navigation is less useful.

**Comment by zell-mbc** [comment]
> You can navigate forward and backward on the details page in the upper right corner. When the save closes this page, the navigation is less useful.

Didn't spot that one yet, you are right with that little control closing the page on save makes no sense.

**Comment by holocronology** [comment]
> On my DietPi I had to install pip/requests first but after that everything seems to work.

Do you have pihole and unbound on this dietpi? I can't get this to install properly and end up with a 404 Not Found error.

**Comment by zell-mbc** [comment]
I did have both running on the same Pi, but not any longer as I moved my PiHole over to a LXC container and didn't yet install PiAlert again.
