### ISSUE TITLE
Error when setting up Pi.Alert with special characters inside SMTP password

### ISSUE THREAD

**Issue by Striffly** [leiweibau/Pi.Alert#202]
Hello

When I setting up Pi.Alert with the automated script, I have also inserted the SMTP parameters for sending mail.
My password contains the `(` characters.

During further installation, I encountered this error :
```
- Prepare directories...
*** PLEASE WAIT A COUPLE OF MINUTES...

Traceback (most recent call last):
  File "/home/xxxx/pialert/back/pialert.py", line 41, in <module>
    exec(open(PIALERT_PATH + "/config/pialert.conf").read())
  File "<string>", line 35
    SMTP_PASS         = 'xxxxx)xxxxx'
                              ^

- Testing Pi.Alert Internet IP Lookup...
Traceback (most recent call last):
  File "/home/xxxx/pialert/back/pialert.py", line 41, in <module>
    exec(open(PIALERT_PATH + "/config/pialert.conf").read())
  File "<string>", line 35
    SMTP_PASS         = 'xxxxx)xxxxx'
                              ^

- Testing Pi.Alert Network scan...
*** PLEASE WAIT A COUPLE OF MINUTES...

Traceback (most recent call last):
  File "/home/xxxx/pialert/back/pialert.py", line 41, in <module>
    exec(open(PIALERT_PATH + "/config/pialert.conf").read())
  File "<string>", line 35
    SMTP_PASS         = 'xxxxx)xxxxx'
                              ^
```
Due to this error, the installation was not completed correctly (not all my devices were detected).
I re-run the installation without defining SMTP, and this time the installation was successful.

**Comment by leiweibau** [comment]
Thanks for reporting this error. I will have a look at it.

**Comment by leiweibau** [comment]
Should be fixed with this release https://github.com/leiweibau/Pi.Alert/commit/8b8924d702425eced334561c927d2ca21008825f
