### ISSUE TITLE
[Documentation] Pihole database Issue On Install

### ISSUE THREAD

**Issue by blakeforcier** [leiweibau/Pi.Alert#430]
When I run the one-line install and after some basic troubleshooting, I'm unable to get this to resolve:

- Testing Pi.Alert Network scan...
*** PLEASE WAIT A COUPLE OF MINUTES...

Pi.Alert v2024-12-12
---------------------------------------------------------
Executing user: bforce
Timestamp: 2024-12-24 17:23:00

Scanning...
    arp-scan Method...
    arp-scan: One interface
    Pi-hole 5 Client List Method...
Traceback (most recent call last):
  File "/home/bforce/pialert/back/pialert.py", line 4031, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bforce/pialert/back/pialert.py", line 102, in main
    res = scan_network()
          ^^^^^^^^^^^^^^
  File "/home/bforce/pialert/back/pialert.py", line 826, in scan_network
    copy_pihole_network()
  File "/home/bforce/pialert/back/pialert.py", line 1026, in copy_pihole_network
    copy_pihole_network_five()
  File "/home/bforce/pialert/back/pialert.py", line 1036, in copy_pihole_network_five
    sql.execute ("ATTACH DATABASE '"+ PIHOLE_DB +"' AS PH")
sqlite3.DatabaseError: file is not a database

**Comment by blakeforcier** [comment]
I found the cause. pihole-FTL.db was corrupt. I solved it by:

- sudo service pihole-FTL stop
- sudo rm /etc/pihole/pihole-FTL.db
- sudo service pihole-FTL start

Then kicked off a new scan from pi.alert and it all went through fine.
